//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointOfSale.MenuService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/PointOfSale.Models")]
    [System.SerializableAttribute()]
    public partial class Category : PointOfSale.MenuService.ModelBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PointOfSale.MenuService.MenuItem[] MenuItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PointOfSale.MenuService.MenuItem[] MenuItems {
            get {
                return this.MenuItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.MenuItemsField, value) != true)) {
                    this.MenuItemsField = value;
                    this.RaisePropertyChanged("MenuItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModelBase", Namespace="http://schemas.datacontract.org/2004/07/PointOfSale.Models")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PointOfSale.MenuService.MenuItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PointOfSale.MenuService.Category))]
    public partial class ModelBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MenuItem", Namespace="http://schemas.datacontract.org/2004/07/PointOfSale.Models")]
    [System.SerializableAttribute()]
    public partial class MenuItem : PointOfSale.MenuService.ModelBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PointOfSale.MenuService.Category CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PointOfSale.MenuService.Category Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryId {
            get {
                return this.CategoryIdField;
            }
            set {
                if ((this.CategoryIdField.Equals(value) != true)) {
                    this.CategoryIdField = value;
                    this.RaisePropertyChanged("CategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MenuService.IMenuServcie")]
    public interface IMenuServcie {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuServcie/GetCategories", ReplyAction="http://tempuri.org/IMenuServcie/GetCategoriesResponse")]
        PointOfSale.MenuService.Category[] GetCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuServcie/GetCategories", ReplyAction="http://tempuri.org/IMenuServcie/GetCategoriesResponse")]
        System.Threading.Tasks.Task<PointOfSale.MenuService.Category[]> GetCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuServcie/GetCategory", ReplyAction="http://tempuri.org/IMenuServcie/GetCategoryResponse")]
        PointOfSale.MenuService.Category GetCategory(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuServcie/GetCategory", ReplyAction="http://tempuri.org/IMenuServcie/GetCategoryResponse")]
        System.Threading.Tasks.Task<PointOfSale.MenuService.Category> GetCategoryAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuServcie/GetCategoryMenuItems", ReplyAction="http://tempuri.org/IMenuServcie/GetCategoryMenuItemsResponse")]
        PointOfSale.MenuService.MenuItem[] GetCategoryMenuItems(int categoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuServcie/GetCategoryMenuItems", ReplyAction="http://tempuri.org/IMenuServcie/GetCategoryMenuItemsResponse")]
        System.Threading.Tasks.Task<PointOfSale.MenuService.MenuItem[]> GetCategoryMenuItemsAsync(int categoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuServcie/GetMenuItem", ReplyAction="http://tempuri.org/IMenuServcie/GetMenuItemResponse")]
        PointOfSale.MenuService.MenuItem GetMenuItem(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuServcie/GetMenuItem", ReplyAction="http://tempuri.org/IMenuServcie/GetMenuItemResponse")]
        System.Threading.Tasks.Task<PointOfSale.MenuService.MenuItem> GetMenuItemAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuServcie/SaveMenuItem", ReplyAction="http://tempuri.org/IMenuServcie/SaveMenuItemResponse")]
        PointOfSale.MenuService.MenuItem SaveMenuItem(PointOfSale.MenuService.MenuItem menuItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuServcie/SaveMenuItem", ReplyAction="http://tempuri.org/IMenuServcie/SaveMenuItemResponse")]
        System.Threading.Tasks.Task<PointOfSale.MenuService.MenuItem> SaveMenuItemAsync(PointOfSale.MenuService.MenuItem menuItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuServcie/SaveCategory", ReplyAction="http://tempuri.org/IMenuServcie/SaveCategoryResponse")]
        PointOfSale.MenuService.Category SaveCategory(PointOfSale.MenuService.Category category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuServcie/SaveCategory", ReplyAction="http://tempuri.org/IMenuServcie/SaveCategoryResponse")]
        System.Threading.Tasks.Task<PointOfSale.MenuService.Category> SaveCategoryAsync(PointOfSale.MenuService.Category category);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMenuServcieChannel : PointOfSale.MenuService.IMenuServcie, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MenuServcieClient : System.ServiceModel.ClientBase<PointOfSale.MenuService.IMenuServcie>, PointOfSale.MenuService.IMenuServcie {
        
        public MenuServcieClient() {
        }
        
        public MenuServcieClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MenuServcieClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MenuServcieClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MenuServcieClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PointOfSale.MenuService.Category[] GetCategories() {
            return base.Channel.GetCategories();
        }
        
        public System.Threading.Tasks.Task<PointOfSale.MenuService.Category[]> GetCategoriesAsync() {
            return base.Channel.GetCategoriesAsync();
        }
        
        public PointOfSale.MenuService.Category GetCategory(int id) {
            return base.Channel.GetCategory(id);
        }
        
        public System.Threading.Tasks.Task<PointOfSale.MenuService.Category> GetCategoryAsync(int id) {
            return base.Channel.GetCategoryAsync(id);
        }
        
        public PointOfSale.MenuService.MenuItem[] GetCategoryMenuItems(int categoryId) {
            return base.Channel.GetCategoryMenuItems(categoryId);
        }
        
        public System.Threading.Tasks.Task<PointOfSale.MenuService.MenuItem[]> GetCategoryMenuItemsAsync(int categoryId) {
            return base.Channel.GetCategoryMenuItemsAsync(categoryId);
        }
        
        public PointOfSale.MenuService.MenuItem GetMenuItem(int id) {
            return base.Channel.GetMenuItem(id);
        }
        
        public System.Threading.Tasks.Task<PointOfSale.MenuService.MenuItem> GetMenuItemAsync(int id) {
            return base.Channel.GetMenuItemAsync(id);
        }
        
        public PointOfSale.MenuService.MenuItem SaveMenuItem(PointOfSale.MenuService.MenuItem menuItem) {
            return base.Channel.SaveMenuItem(menuItem);
        }
        
        public System.Threading.Tasks.Task<PointOfSale.MenuService.MenuItem> SaveMenuItemAsync(PointOfSale.MenuService.MenuItem menuItem) {
            return base.Channel.SaveMenuItemAsync(menuItem);
        }
        
        public PointOfSale.MenuService.Category SaveCategory(PointOfSale.MenuService.Category category) {
            return base.Channel.SaveCategory(category);
        }
        
        public System.Threading.Tasks.Task<PointOfSale.MenuService.Category> SaveCategoryAsync(PointOfSale.MenuService.Category category) {
            return base.Channel.SaveCategoryAsync(category);
        }
    }
}
